apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
  namespace: cloudgraph
  labels:
    app: checkout-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: checkout
          image: ghcr.io/open-telemetry/opentelemetry-demo/frontend:v1.8.0
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4317"
            - name: OTEL_SERVICE_NAME
              value: "checkout-service"
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service
  namespace: cloudgraph
  labels:
    app: checkout-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: checkout-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: cloudgraph
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: payment
          image: ghcr.io/open-telemetry/opentelemetry-demo/productcatalogservice:v1.8.0
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4317"
            - name: OTEL_SERVICE_NAME
              value: "payment-service"
            - name: PORT
              value: "8081"
          ports:
            - containerPort: 8081
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: cloudgraph
  labels:
    app: payment-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  selector:
    app: payment-service
