namespace: cloudgraph

otelCollectorEndpoint: "http://otel-collector.observability.svc.cluster.local:4317"

checkout:
  name: checkout-service
  replicaCount: 1
  image:
    repository: ghcr.io/open-telemetry/opentelemetry-demo/frontend
    tag: v1.8.0
    pullPolicy: IfNotPresent
  port: 8080

payment:
  name: payment-service
  replicaCount: 1
  image:
    repository: ghcr.io/open-telemetry/opentelemetry-demo/productcatalogservice
    tag: v1.8.0
    pullPolicy: IfNotPresent
  port: 8081
